
const CommList = [
    {
        cate: '진로 고민',
        title: '제가 php 2년차 웹개발자인데.. Node로 이직이 가능할까요?',
        contents: '현재 1년 쉬면서 Node 사용하는 회사로 이직하려고 합니다.\n만약 그렇게된다면 php를 사용해서 웹개발 했던 경력은 물경력이 되는건가요? ',
        writer: '김구함',
        views: 1,
        comments: 0,
        oneW:'',
        one:'',
        twoW:'',
        two:'',
        threeW:'',
        three:''
    },
    {
        cate: '진로 고민',
        title: '컴퓨터 공학 전공자',
        contents: '컴퓨터 공학 전공자로서 더미 데이터와 관련한 이직 고민을 풀고 싶습니다. 더미 데이터와 컴퓨터 공학에 대한 생각을 나누어주세요.',
        writer: '이구함',
        views: 5,
        comments: 0,
        oneW:'',
        one:'',
        twoW:'',
        two:'',
        threeW:'',
        three:''
    },
    {
        cate: '자유 주제',
        title: '햄최몇',
        contents: '제곧내',
        writer: '이구함',
        views: 10,
        comments: 2,
        oneW:'문돼',
        one:'10',
        twoW:'허각',
        two:'30',
        threeW:'',
        three:''
    },
    {
        cate: 'QnA',
        title: '프론트엔드와 백엔드 차이',
        contents: '프론트엔드와 백엔드 개발의 주요 차이점이 무엇인지 궁금합니다. 프론트엔드 및 백엔드 개발자로서 무엇을 고려해야 하는지 알려주세요.',
        writer: '박구함',
        views: 6,
        comments: 0,
        oneW:'',
        one:'',
        twoW:'',
        two:'',
        threeW:'',
        three:''
    },
    {
        cate: 'QnA',
        title: 'docker 활용 방법 다들 어떻게 하고 계신가요?',
        contents: '혼자 취미로 개발하고 있는데, 리눅스 머신에서 혼자 하다보니 docker 장점을 잘 살리고 있지 못한거 같아서요.. spring이랑 db 각각 포트 다르게 띄워서 사용하는거랑 container 각각 하나씩 띄운 후 spring이랑 db 설치해서 사용하는거랑 비교하면 차이가 나지 않는것 같네요. \n\n혹시 혼자 개발하실 때 좀 더 잘 활용해서 사용하는 방법이 있을까요?\n\ncase 1 : 리눅스 머신에 spring, mysql 모두 띄워서 사용\n case 2 : docker container에 각각 spring, mysql 띄워서 사용\n\n 다들 어떻게 사용하시는지 궁금합니다. 현업에서는 어떻게 활용하고 있는지도 공유해주시면 감사하겠습니다(_ _)',
        writer: '박구함',
        views: 3,
        comments: 0,
        oneW:'',
        one:'',
        twoW:'',
        two:'',
        threeW:'',
        three:''
    },
    
    {
        cate: 'QnA',
        title: 'React 컴포넌트를 어떻게 최적화할 수 있을까요?',
        contents: '안녕하세요, React 개발을 하고 있는데 컴포넌트 최적화에 대한 조언이 필요합니다. 더 나은 성능을 위해 어떤 방법을 사용하는지 공유해주세요.',
        writer: '박구함',
        views: 4,
        comments: 2,
        oneW:'김구함',
        one:'React 앱을 최적화하는 데 두 가지 주요 방법은 React Memoization을 활용하여 불필요한 렌더링을 방지하고, 코드 스플리팅을 사용하여 필요한 컴포넌트 및 자원만 로드하는 방법이 있어요',
        twoW:'이구함',
        two:'또 다른 방법은 불필요한 렌더링을 방지하고 성능을 향상하기 위해 가상 DOM을 최적화하거나, 컴포넌트를 작게 분할하여 재사용성을 높이는 방법도 있구요',
        threeW:'',
        three:''
    },
    {
        cate: '진로 고민',
        title: 'Node.js로의 이직 가능할까요?',
        contents: '안녕하세요, 현재 PHP로 2년차 웹 개발자로 일하고 있습니다. 최근 Node.js에 관심이 생겨서 언어를 변경한 후 이직이 가능할까요? 경력과 관련해서 조언을 구하려고 합니다.',
        writer: '김구함',
        views: 1,
        comments: 0,
        oneW:'',
        one:'',
        twoW:'',
        two:'',
        threeW:'',
        three:''
    },
    {
        cate: 'QnA',
        title: 'Docker 사용법에 대한 조언 부탁드립니다.',
        contents: '안녕하세요, 개인 프로젝트로 리눅스 머신에서 도커를 사용하고 있는데, 더 효율적으로 활용하는 방법이 있을까요? Spring 및 MySQL을 도커 컨테이너에서 사용하는 방법에 대한 조언을 기다리고 있습니다.',
        writer: '박구함',
        views: 3,
        comments: 0,
        oneW:'',
        one:'',
        twoW:'',
        two:'',
        threeW:'',
        three:''
    },
    {
        cate: '자유 주제',
        title: '안녕하세요!',
        contents: '안녕하세요, 간단한 인사를 드립니다. 이곳에서 다양한 주제로 이야기하고 싶어서 찾아왔습니다. 함께 이야기하면 더 재미있을 것 같아요!',
        writer: '이구함',
        views: 10,
        comments: 0,
        oneW:'',
        one:'',
        twoW:'',
        two:'',
        threeW:'',
        three:''
    },
];


export default CommList;
